name: Build Hunt Analyzer

on:
  push:
    tags:
      - 'v*'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4   # já compatível com Node 24
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install customtkinter bcrypt pillow matplotlib pyinstaller
      - name: Build exe
        run: python -m PyInstaller HuntAnalyzer.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HuntAnalyzer-Windows
          path: dist/HuntAnalyzer.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # já compatível com Node 24
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install customtkinter bcrypt pillow matplotlib pyinstaller
      - name: Build exe
        run: python -m PyInstaller HuntAnalyzer.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HuntAnalyzer-Linux
          path: dist/HuntAnalyzer
